{"code": 0, "msg": "FAIL", "task_id": "2022101204584786239715", "task_name": "whole process", "create_time": "20221012045847862537", "error": "Traceback (most recent call last):\n  File \"/home/jit/service/mpc/driver/task.py\", line 60, in persist\n    r = self.__future.result()\n  File \"/usr/lib/python3.6/concurrent/futures/_base.py\", line 425, in result\n    return self.__get_result()\n  File \"/usr/lib/python3.6/concurrent/futures/_base.py\", line 384, in __get_result\n    raise self._exception\n  File \"/usr/lib/python3.6/concurrent/futures/thread.py\", line 56, in run\n    result = self.fn(*self.args, **self.kwargs)\n  File \"/home/jit/service/mpc/SrcCode/main_dynamic_function.py\", line 29, in start_mpc\n    dv = DynamicVariables(config_cpt)\n  File \"/home/jit/service/mpc/SrcCode/Source/dynamic_function.py\", line 174, in __init__\n    raise ValueError('THERE ARE NOT SUPPORTED OPERATORS')\nValueError: THERE ARE NOT SUPPORTED OPERATORS\n"}