{"code": 0, "msg": "FAIL", "task_id": "2022123005404447834820", "task_name": "whole process", "create_time": "20221230054044478416", "error": "Traceback (most recent call last):\n  File \"/home/jit/service/mpc/driver/task.py\", line 60, in persist\n    r = self.__future.result()\n  File \"/usr/lib/python3.6/concurrent/futures/_base.py\", line 425, in result\n    return self.__get_result()\n  File \"/usr/lib/python3.6/concurrent/futures/_base.py\", line 384, in __get_result\n    raise self._exception\n  File \"/usr/lib/python3.6/concurrent/futures/thread.py\", line 56, in run\n    result = self.fn(*self.args, **self.kwargs)\n  File \"/home/jit/service/mpc/SrcCode/main_dynamic_function.py\", line 30, in start_mpc\n    res = dv.eval_formula()\n  File \"/home/jit/service/mpc/SrcCode/Source/dynamic_function.py\", line 242, in eval_formula\n    step_results_ai = sfix.Matrix(self.num_ai, self.d_ai)\n  File \"/home/jit/service/mpc/Compiler/types.py\", line 505, in Matrix\n    return Matrix(rows, columns, cls, *args, **kwargs)\n  File \"/home/jit/service/mpc/Compiler/types.py\", line 6441, in __init__\n    address=address)\n  File \"/home/jit/service/mpc/Compiler/types.py\", line 6410, in __init__\n    self.array = Array(reduce(operator.mul, sizes), \\\nTypeError: unsupported operand type(s) for *: 'int' and 'NoneType'\n"}